spring:
  # 数据库配置信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/small_rookie_normal?useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # 连接超时时间（毫秒）
    timeout: 60000
    password:
    lettuce:
      pool:
        # 最大活跃链接数 默认8
        max-active: 1000
        # 最大空闲连接数 默认8
        max-idle: 10
        # 最小空闲连接数 默认0
        min-idle: 0  
  # 设置返回日期格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
# mybatis配置信息
mybatis:
  type-aliases-package: com.zdxj.model
  mapper-locations: classpath:mappers/*.xml
#hystrix的超时时间
hystrix:
  threadpool:
    default:
      #并发执行的最大线程数，默认10
      coreSize: 300
      #BlockingQueue的最大队列数
      maxQueueSize: 1500
      #即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
      queueSizeRejectionThreshold: 1000
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 240000
#ribbon的超时时间
ribbon:
  ReadTimeout: 120000
  ConnectTimeout: 120000
# 阿里云图片服务器  
aliyun:
  image:
    accessKeyId: ****
    accessKeySecret: ****
    bucketName: ****
    endpoint: ****
    bucketUrl: ****